apiVersion: apps/v1
kind: Deployment
metadata:
  name: stroe
  labels:
    app: stroe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stroe
  template:
    metadata:
      labels:
        app: stroe
    spec:
      containers:
        - name: stroe
          image: "username/stroe:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
